Temporarly commented the package ci/cd to redeploy back office

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,52 +13,63 @@ default:
     - NPM_PACKAGE_VERSION=$(node -p "require('./projects/who-ems/package.json').version")
 
 stages:
-  - build
+  # - build
   - deploy
 
-# Validate that the package name is properly scoped to the project's root namespace.
-# For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention
-validate_package_scope:
-  stage: build
-  script:
-    - |
-      if [[ ! $NPM_PACKAGE_NAME =~ ^@$CI_PROJECT_ROOT_NAMESPACE/ ]]; then
-        echo "Invalid package scope! Packages must be scoped in the root namespace of the project, e.g. \"@${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}\""
-        echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention'
-        exit 1
-      fi
+# validate_package_scope:
+#   stage: build
+#   script:
+#     - |
+#       if [[ ! $NPM_PACKAGE_NAME =~ ^@$CI_PROJECT_ROOT_NAMESPACE/ ]]; then
+#         echo "Invalid package scope! Packages must be scoped in the root namespace of the project, e.g. \"@${CI_PROJECT_ROOT_NAMESPACE}/${CI_PROJECT_NAME}\""
+#         echo 'For more information, see https://docs.gitlab.com/ee/user/packages/npm_registry/#package-naming-convention'
+#         exit 1
+#       fi
 
-# If no .npmrc if included in the repo, generate a temporary one to use during the publish step
-# that is configured to publish to GitLab's NPM registry
-create_npmrc:
-  stage: build
-  script:
-    - |
-      echo '${CI_JOB_TOKEN}'
-      if [[ ! -f .npmrc ]]; then
-        echo 'No .npmrc found! Creating one now. Please review the following link for more information: https://docs.gitlab.com/ee/user/packages/npm_registry/index.html#authenticating-with-a-ci-job-token'
+# create_npmrc:
+#   stage: build
+#   script:
+#     - |
+#       echo '${CI_JOB_TOKEN}'
+#       if [[ ! -f .npmrc ]]; then
+#         echo 'No .npmrc found! Creating one now. Please review the following link for more information: https://docs.gitlab.com/ee/user/packages/npm_registry/index.html#authenticating-with-a-ci-job-token'
 
-        {
-          echo '@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_SERVER_PROTOCOL}://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
-          echo '//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}'
-          echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'
-        } >> .npmrc
+#         {
+#           echo '@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_SERVER_PROTOCOL}://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/'
+#           echo '//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}'
+#           echo '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}'
+#         } >> .npmrc
 
-      fi
-  artifacts:
-    paths:
-      - .npmrc
+#       fi
+#   artifacts:
+#     paths:
+#       - .npmrc
 
-# Publish the package. If the version in package.json has not yet been published, it will be
-# published to GitLab's NPM registry. If the version already exists, the publish command
-# will fail and the existing package will not be updated.
-publish_package:
+# publish_package:
+#   stage: deploy
+#   script:
+#     - |
+#       {
+#         npm publish ./projects/who-ems &&
+#         echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} to GitLab's NPM registry: ${CI_PROJECT_URL}/-/packages"
+#       } || {
+#         echo "No new version of ${NPM_PACKAGE_NAME} published. This is most likely because version ${NPM_PACKAGE_VERSION} already exists in GitLab's NPM registry."; exit 1
+#       }
+
+deploy_back_office:
   stage: deploy
+  before_script:
+    - apt-get update -qq
+    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
+    - eval $(ssh-agent -s)
+    - ssh-add <(echo "$SSH_PRIVATE_KEY")
+    - mkdir -p ~/.ssh
+    - chmod 700 ~/.ssh
+    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
+    - chmod 644 ~/.ssh/known_hosts  
+    - npm i
   script:
-    - |
-      {
-        npm publish ./projects/who-ems &&
-        echo "Successfully published version ${NPM_PACKAGE_VERSION} of ${NPM_PACKAGE_NAME} to GitLab's NPM registry: ${CI_PROJECT_URL}/-/packages"
-      } || {
-        echo "No new version of ${NPM_PACKAGE_NAME} published. This is most likely because version ${NPM_PACKAGE_VERSION} already exists in GitLab's NPM registry."; exit 1
-      }
+    - npm run build -- --prod
+    - ./CI/deploy-back-office.sh
+  only:
+    - dev
